/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CaptureNotice: typeof import('./components/CaptureNotice.vue')['default']
    Composer: typeof import('./components/Composer.vue')['default']
    DropdownMenu: typeof import('./components/ui/dropdown-menu/DropdownMenu.vue')['default']
    DropdownMenuCheckboxItem: typeof import('./components/ui/dropdown-menu/DropdownMenuCheckboxItem.vue')['default']
    DropdownMenuContent: typeof import('./components/ui/dropdown-menu/DropdownMenuContent.vue')['default']
    DropdownMenuGroup: typeof import('./components/ui/dropdown-menu/DropdownMenuGroup.vue')['default']
    DropdownMenuItem: typeof import('./components/ui/dropdown-menu/DropdownMenuItem.vue')['default']
    DropdownMenuLabel: typeof import('./components/ui/dropdown-menu/DropdownMenuLabel.vue')['default']
    DropdownMenuRadioGroup: typeof import('./components/ui/dropdown-menu/DropdownMenuRadioGroup.vue')['default']
    DropdownMenuRadioItem: typeof import('./components/ui/dropdown-menu/DropdownMenuRadioItem.vue')['default']
    DropdownMenuSeparator: typeof import('./components/ui/dropdown-menu/DropdownMenuSeparator.vue')['default']
    DropdownMenuShortcut: typeof import('./components/ui/dropdown-menu/DropdownMenuShortcut.vue')['default']
    DropdownMenuSub: typeof import('./components/ui/dropdown-menu/DropdownMenuSub.vue')['default']
    DropdownMenuSubContent: typeof import('./components/ui/dropdown-menu/DropdownMenuSubContent.vue')['default']
    DropdownMenuSubTrigger: typeof import('./components/ui/dropdown-menu/DropdownMenuSubTrigger.vue')['default']
    DropdownMenuTrigger: typeof import('./components/ui/dropdown-menu/DropdownMenuTrigger.vue')['default']
    EditorRecoveryRow: typeof import('./components/EditorRecoveryRow.vue')['default']
    IconLucideEllipsis: typeof import('~icons/lucide/ellipsis')['default']
    IconLucideSearch: typeof import('~icons/lucide/search')['default']
    NoteBody: typeof import('./components/NoteBody.vue')['default']
    NoteCard: typeof import('./components/NoteCard.vue')['default']
    NoteEditor: typeof import('./components/NoteEditor.vue')['default']
    NoteList: typeof import('./components/NoteList.vue')['default']
    PanelHeader: typeof import('./components/PanelHeader.vue')['default']
    PanelMenu: typeof import('./components/PanelMenu.vue')['default']
    PanelShell: typeof import('./components/PanelShell.vue')['default']
    PanelStates: typeof import('./components/PanelStates.vue')['default']
    SectionHeader: typeof import('./components/SectionHeader.vue')['default']
  }
}
